In [31]:
import numpy as np 

In [ ]:
#ARRAYS

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [18]:
a = np.array([1,3,5,7,12])
a

array([ 1,  3,  5,  7, 12])

In [24]:
# Obtener un valor de un array. Indexacion arranca en 0
a[3]
# Para cambiar un elemento del array
a[3] = 8
a

array([ 1,  3,  5,  8, 12])

In [27]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [32]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [33]:
# MULTI-DIMENSIONAL ARRAYS

In [34]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
n = np.array ([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n [0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [45]:
n[2] = [1,1,1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [51]:
n[:, 2] = [0,1,2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [52]:
#GENERACION DE ARRAYS RAMDON

In [54]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [55]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [56]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [58]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

In [59]:
#OPERACION POR ELEMENTOS

In [78]:
a = np.arange(5) 
a

array([0, 1, 2, 3, 4])

In [79]:
b = 10+ (a * 2) ** 2 / 100 
b

array([10.  , 10.04, 10.16, 10.36, 10.64])

In [80]:
a / b + 10 # Cualquier operacion

array([10.        , 10.09960159, 10.19685039, 10.28957529, 10.37593985])

In [81]:
#COMPARACION DE OPERACIONES

In [84]:
a = a * 10
c = a > b
c

array([False, False,  True,  True,  True])

In [85]:
a[a > b] #Devuelve todos los elementos de la matriz a que cumplan la condicion

array([20, 30, 40])

In [86]:
#OPERACION AGREGADAS (SUMMARIZING COMPARICION)

In [87]:
a

array([ 0, 10, 20, 30, 40])

In [97]:
a.min()

np.int64(0)

In [93]:
a.sum()

np.int64(100)

In [98]:
a.max()

np.int64(40)

In [99]:
a.mean()

np.float64(20.0)