In [43]:
import numpy as np

In [37]:
#VECTOR OPERATION

In [38]:
u = np.array ([2,4,5,6])
v = np.array ([1,0,0,2])
u + v

array([3, 4, 5, 8])

In [39]:
u * v

array([ 2,  0,  0, 12])

In [40]:
#PRODUCTO ESCALAR (DOT PRODUCT)

In [41]:
def multiplicacion_vector_vector(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result
multiplicacion_vector_vector (u,v)




np.float64(14.0)

In [ ]:
u.dot(v) # Como calcular con NP sin escribir todo el codigo

np.int64(14)

In [44]:
#MULTIPLIACION MATRIZ - VECTOR

In [84]:
U = np.array([
              [2,4,5,6],
              [1,2,1,2],
              [3,1,2,1]
              ])
v = np.array([1,0.5,2,1])
U.shape[0]

3

In [80]:
def Multiplicacion_Matrix_Vector(U,v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = multiplicacion_vector_vector (U[i],v)

    return result

Multiplicacion_Matrix_Vector(U,v)



array([20. ,  6. ,  8.5])

In [ ]:
U.dot(v) # Como calcular con NP sin escribir todo el codigo

array([20. ,  6. ,  8.5])

In [ ]:
# MULTIPLICACION MATRIZ - MATRIZ

In [93]:
U = np.array([
              [2,4,5,6],
              [1,2,1,2],
              [3,1,2,1]
              ])
V = np.array([
              [2,1,2],
              [0,0.5,1],
              [0,2,1],
              [2,1,0]
              ])


In [102]:
def Multiplicacion_matrix_matrix(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = Multiplicacion_Matrix_Vector(U, vi)
        result[:, i] = Uvi
    
    return result

Multiplicacion_matrix_matrix(U, V)

array([[16. , 20. , 13. ],
       [ 6. ,  6. ,  5. ],
       [ 8. ,  8.5,  9. ]])

In [ ]:
U.dot(V) #Como calcular con NP sin escribir todo el codigo

array([[16. , 20. , 13. ],
       [ 6. ,  6. ,  5. ],
       [ 8. ,  8.5,  9. ]])

In [104]:
# MATRIX IDENTIDAD

In [113]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [114]:
V.dot(I)

array([[2. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [116]:
# INVERSA
Vs = np.array([[2. , 1. , 2. ],
                [0. , 0.5, 1. ],
                [0. , 2. , 1. ]])
Vs

array([[2. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [117]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 0.5       , -1.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [119]:
Vs.dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])